#include "g.h"
#include gGG

G GGG GGGGGGGGGG
GGGGGGG
G GGG GGGGGGGGGGGGGGGGG
	_G GGGGGGGGG __g GGGGGGGGGGGGGGGGG
	_GG
	_G GGGGGGGGG __gg GGGGGGGGGGGGGGGGG
	_GG
	Gg GG_G GGGGGGGGGGGGGGGGG
	_GGG GG_G GGGGGGGGGGGGGGGGG
	_G GGGGGGGGG GG_G + " " + __ggg GGGGGGGGGGGGGGGGG
	_GG _GG
	_G GGGGGGGGG __gggg GGGGGGGGGGGGGGGGG
	Gg GG_GG GGGGGGGGGGGGGGGGG
	_GGG GG_GG GGGGGGGGGGGGGGGGG
	GGGGGGGGGGGGGGGGGG GGGGGGGGGGg GG_GG GGGGGGGGGGGGGGGGGGG GGGGGGGGGGg ___g GGGGGGGGGGgg GGGGGGGGGGgg GGGGGGG
		_G GGGGGGGGG __ggggg GGGGGGGGGGGGGGGGG
	GGGGGGGG GGGGGGGGGGGGGGGGGGgg GGGGGGGGGGg GG_GG GGGGGGGGGGGGGGGGGGG GGGGGGGGGGg ___gg GGGGGGGGGGgg GGGGGGGGGGgg GGGGGGG
		_G GGGGGGGGG __gggggg GGGGGGGGGGGGGGGGG
	GGGGGGGG GGGGGGGGGGGGGGGGGGg GGGGGGG
		_G GGGGGGGGG __ggggggg GGGGGGGGGGGGGGGGG
	GGGGGGGG
	gGgG GGGGGGGGGGGGGGGGG
GGGGGGGG
